name: CI Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Python Version Check - 21f1003667@ds.study.iitm.ac.in
        run: |
          python3 --version

      - name: Echo Email Step
        run: echo "Hello, world!"
